services:
  geolocalisation:
    build:
      context: ./service_geolocalisation
    ports:
      - "5001:5001"
    networks:
      - foodgo
    volumes:
      - ./service_geolocalisation/logs:/app/logs
    environment:
      - EUREKA_SERVER=http://eureka:8761/
      - EUREKA_APP_NAME=ServiceGeolocalisation
      - EUREKA_INSTANCE_HOST=geolocalisation
      - EUREKA_PORT=5001
    depends_on:
      - postgres

  payment:
    build:
      context: ./service_payment
    ports:
      - "5002:5002"
    networks:
      - foodgo
    volumes:
      - ./service_payment/logs:/app/logs
    environment:
      - EUREKA_SERVER=http://eureka:8761/
      - EUREKA_APP_NAME=ServicePayment
      - EUREKA_INSTANCE_HOST=payment
      - EUREKA_PORT=5002
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: prosper
      POSTGRES_PASSWORD: prosper
      POSTGRES_DB: prosper
    ports:
      - "5430:5432"
    networks:
      - foodgo
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  foodgo:
    driver: bridge

volumes:
  postgres_data:
