version: '3.3'

services:
  geolocalisation:
    build:
      context: ./service_geolocalisation
    ports:
      - "5001:5001"
    networks:
      - foodgo
    volumes:
      - ./service_geolocalisation/logs:/app/logs

  payment:
    build:
      context: ./service_payment
    ports:
      - "5002:5002"
    networks:
      - foodgo
    volumes:
      - ./service_payment/logs:/app/logs

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: prosper
      POSTGRES_PASSWORD: prosper
      POSTGRES_DB: prosper
    ports:
      - "5432:5432"
    networks:
      - foodgo
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  foodgo:
    driver: bridge

volumes:
  postgres_data:
