spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      route:
        - id: route_dao
          uri: lb://foodGo-dao
          predicates:
            - Path=/**
        - id: route_userAccount
          uri: lb://foodGo-ConnexionEtComptes
          predicates:
            - Path=/**

  server:
    port: 6000
    eureka:
      client:
        service-url:
          defaultZone: http://37.60.244.227:8761/eureka/
        register-with-eureka: true
        instance:
          prefer-ip-address: true
