spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      route:
        - id: my_route
          uri: lb://foodGo-dao
          predicates:
            - Path=/**

  server:
    port: 8088
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        instance:
          prefer-ip-address: true