routes:
- id: dao
  uri: lb://FOODGO-DAO
  predicates:
    - Path=/dao/**
  filters:
    - StripPrefix=1
  order: -1
- id: user_account
  uri: lb://FOODGO-CONNEXIONETCOMPTES
  predicates:
    - Path=/user-management/**
  filters:
    - StripPrefix=1
    
- id: location
  uri: lb://GEOLOCALISATION-SERVICE
  predicates:
    - Path=/geolocalisation/**
  filters:
    - StripPrefix=1
    
- id: payment
  uri: lb://PAYMENT-SERVICE
  predicates:
    - Path=/payment/**
  filters:
    - StripPrefix=1

eureka:
client:
service-url:
  defaultZone: http://localhost:8761/eureka/
register-with-eureka: true
instance:
  prefer-ip-address: true
